### ISSUE TITLE
TileEntities duping

### ISSUE THREAD

**Issue by knoxhack** [elytra/Oops#2]
If you click a tile entity while holding some of the same in your hand you get the double amount of the ones you are holding.
For example if you are holder a stack in your hand if you place one and then you break it you get an extra stack back not just one.
Thanks

Forge: 1.12.2-14.23.0.2515
Mod Version: oops-1.12-3.6

**Comment by darkevilmac** [comment]
Does this happen with vanilla tile entities (Furnaces, Chests, Dispensers,
etc.), or is this happening with a modded tile entity?

**Comment by knoxhack** [comment]
Yes, it happens with vanilla tile entities, tried with chests. And the modded tile I tried was the power cell from rf tools.

**Comment by darkevilmac** [comment]
Odd, will take a look.

Are you testing in SinglePlayer or Multiplayer?

**Comment by knoxhack** [comment]
on a multiplayer server im hosting for my modpack.
here maybe you can replicate with it.
https://minecraft.curseforge.com/projects/project-ultimate-reloaded

**Comment by darkevilmac** [comment]
I downloaded that pack, opened the server that was listed in the client. Couldn't reproduce the bug.

**Comment by darkevilmac** [comment]
I think I found what may be the cause, were you using silk touch? If so the next build will fix your problem.

**Comment by knoxhack** [comment]
Wasn't using sill touch, broke the block with the same tile entity

**Comment by darkevilmac** [comment]
Give the new build a try either way. The only part I could think of to cause the issue was changed.

**Comment by knoxhack** [comment]
Will do, thanks for looking into this. Will let you know if it still happening
